# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.provider.example.com:
  peer1.provider.example.com:
  peer0.consumer.example.com:
  peer1.consumer.example.com:

networks:
  byfn:
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-provider
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.provider.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.provider.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/provider.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerProvider
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-consumer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.consumer.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.consumer.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/consumer.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerConsumer
    networks:
      - byfn

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - byfn

  peer0.provider.example.com:
    container_name: peer0.provider.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.provider.example.com
    networks:
      - byfn

  peer1.provider.example.com:
    container_name: peer1.provider.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.provider.example.com
    networks:
      - byfn

  peer0.consumer.example.com:
    container_name: peer0.consumer.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.consumer.example.com
    networks:
      - byfn

  peer1.consumer.example.com:
    container_name: peer1.consumer.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.consumer.example.com
    networks:
      - byfn
